apiVersion: v1
kind: Service
metadata:
  name: cloud-native-monitoring
spec:
  type: ClusterIP
  selector:
    app: cloud-native-monitoring
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
